### ISSUE TITLE
Signature verification failed.

### ISSUE THREAD

**Issue by bigchangego** [onlyjq04/ali-opensearch-v3#2]
调用search(requestPath, queryBuilder)的时候, OPENSEARCH反馈

 "errors": [
    {
      "code": 4003,
      "message": "Signature verification failed."
    }
  ]

把代码拉下拉, 跑了一下NPM RUN TEST, 报如下错误
 Test Publisher
    √ should build the right publish content body

  Test query builder
    √ Tests query from the ali doc
    √ Tests empty query

  5 passing (45ms)
  1 failing

  1) Header tests
       Get header
         should return the right auth header:

      AssertionError: expected '6c7HriYKxgfuRqXvmqQ9WAPclcA=' to equal 'EG+VyxqNhSsPgdaFYfl5Wd7Pulo='
      + expected - actual

      -6c7HriYKxgfuRqXvmqQ9WAPclcA=
      +EG+VyxqNhSsPgdaFYfl5Wd7Pulo=

      at Context.done (test\Header.spec.ts:19:52)
      at callFnAsync (node_modules\_mocha@5.2.0@mocha\lib\runnable.js:400:21)
      at Test.Runnable.run (node_modules\_mocha@5.2.0@mocha\lib\runnable.js:342:7)
      at Runner.runTest (node_modules\_mocha@5.2.0@mocha\lib\runner.js:455:10)
      at D:\workspace\wnj-server\ali-opensearch-v3-master\node_modules\_mocha@5.2.0@mocha\lib\runner.js:573:12
      at next (node_modules\_mocha@5.2.0@mocha\lib\runner.js:369:14)
      at D:\workspace\wnj-server\ali-opensearch-v3-master\node_modules\_mocha@5.2.0@mocha\lib\runner.js:379:7
      at next (node_modules\_mocha@5.2.0@mocha\lib\runner.js:303:14)
      at Immediate.<anonymous> (node_modules\_mocha@5.2.0@mocha\lib\runner.js:347:5)

---------------------
Windows 7 + Node 8.9.3

**Comment by onlyjq04** [comment]
测试用例中用的是官方文档中的测试assertion参数。
